# Generated by Django 3.2.5 on 2021-07-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('body', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='Time (add)')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=32)),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='URL')),
                ('body', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_required', models.BooleanField(default=True)),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='Time (add)')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time (update)')),
            ],
        ),
    ]
